### ISSUE TITLE
InvalidOperationException using foreach with BeamManager.SingletonInstance.Participants

### ISSUE THREAD

**Issue by bzaPetey** [mixer/interactive-unity-plugin#10] opened 2017-05-19 01:36 UTC
Using a foreach loop errors when trying to change the group for a participant, but works ok if you are using a for loop:

        foreach (BeamParticipant p in BeamManager.SingletonInstance.Participants)
        {
            if (beamParticipants.Contains(p))
                p.Group = playerGroup;
            else
                p.Group = crowdGroup;
        }
Error:
InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.Collections.Generic.List`1+Enumerator[Xbox.Services.Beam.BeamParticipant].VerifyState () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:778)
System.Collections.Generic.List`1+Enumerator[Xbox.Services.Beam.BeamParticipant].MoveNext () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:784)
GameLobby.CreateTeams () (at Assets/Scripts/GameLobby.cs:142)
GameLobby.AddPlayer (Xbox.Services.Beam.BeamParticipant bp) (at Assets/Scripts/GameLobby.cs:119)
GameLobby.OnButton (System.Object sender, Xbox.Services.Beam.BeamButtonEventArgs e) (at Assets/Scripts/GameLobby.cs:174)
Microsoft.Beam.Update () (at Assets/Beam/Source/Scripts/Beam.cs:456)

**Comment by payzer** [comment] 2017-05-19 21:02
Thank you for reporting this. We had a consistent repro, but it's gone now (we copied & pasted the code snippet above). Once we get the repro back, we'll investigate.

**Comment by bzaPetey** [comment] 2017-05-22 14:46
on thing that i forgot to mention is that beamParticipants was just a list of participants that had hit a button to join the game.

**Comment by payzer** [comment] 2017-05-22 15:33
Thank you. We'll keep investigating.

**Comment by payzer** [comment] 2017-05-31 01:11
We think we know what the issue is. We'll get a fix for this.

**Comment by payzer** [comment] 2017-05-31 17:27
Thank you for filing this issue. We have fixed it in the issue in the latest release of the SDK. Let us know if you are still seeing issues.

**Closed by payzer** 2017-05-31 17:27 UTC
