### ISSUE TITLE
Cool downs

### ISSUE THREAD

**Issue by hoggy077** [mixer/interactive-unity-plugin#27] opened 2017-07-29 10:26 UTC
Whilst working on a little something, i noticed that a button set to a minute long cool down, was still at a minute long after being triggered. I set out to investigate further and noticed that all my buttons were getting an extra 25 seconds for no reason. I checked my code and my seconds to milliseconds converter to make sure i hadn't thrown something in during my sleep deprived code session the night before, but to my surprise i couldn't find anything wrong. Thought i would put this out there, I'm not sure if its just me or something bigger.

**Comment by payzer** [comment] 2017-07-29 13:23
Very interesting and thank you for reporting this issue! We will investigate it.

**Comment by hoggy077** [comment] 2017-07-29 23:28
```
void Update(){
        if (MixerInteractive.GetButtonDown("AltT"))
        {
            UnityEngine.Debug.Log("alttab");
            if (AltTa != 0)
            {
                MixerInteractive.TriggerCooldown("AltT", AltTa);
            }
      }
}

````
Seconds to milliseconds converter
````
    public void AltTabInput(string str)
    {
        AltTa = int.Parse(str) * 1000;
    }
````
I have only attached one of each section because the code itself is repetitive for each button. (im lazy, i just copied and pasted my work over again and again so its all the same)

**Comment by payzer** [comment] 2017-07-29 23:34
Thank you for sending the code. The code looks right. For this line, if you debug, is AltTa == 60000?:

MixerInteractive.TriggerCooldown("AltT", AltTa);

**Comment by hoggy077** [comment] 2017-07-30 00:22
AltTa is 60000 when i debug

**Comment by payzer** [comment] 2017-07-30 00:45
That is really strange. Is anything else setting the cooldown? That's the only thing I can think of. When your code sets the cooldown to 60000 the button will start counting down from 59, 58, etc. Are you seeing it set to 1 min 25 sec instead?

**Comment by hoggy077** [comment] 2017-07-30 01:11
The section i posted is the only part handling cool downs, i even took the time to go up in increments of 5 seconds to double check, and every time i get the additional 25 seconds on my page when my project says the set time hasn't changed and the debug of all the variables handling the time say there is no change as well

**Comment by payzer** [comment] 2017-07-30 01:17
Does the example scene have the same behavior (I'm wondering if perhaps there's a difference with your project). The example scene that does cooldowns is under Assets/MixerInteractive/Examples/Throttling input, disabling and setting cooldowns/

You can also share the project (or a minimal repro) and we can take a look.

**Comment by PetePinelli** [comment] 2017-07-31 17:27
I'm getting an issue where my first cooldown will trigger normally, 10 seconds when set at 10000, but any subsequent button presses will display a 7 second cooldown. Also, when I try to output the remaining cooldown time on a button during it's cooldown period, I get an outrageous number which counts down.

There is also some lag between when the cooldown disappears and when I can press the button again, it's typically around an additional 5 seconds.

**Comment by PetePinelli** [comment] 2017-08-03 00:42
`public int cooldownTimeMS = 10000;

void Start () {
        audioSource = GetComponent<AudioSource>();

        MixerInteractive.OnParticipantStateChanged += OnParticipantStateChanged;
        MixerInteractive.OnInteractiveButtonEvent += OnInteractiveButtonEvent;

        MixerInteractive.GoInteractive();
	}

private void OnInteractiveButtonEvent(object sender, InteractiveButtonEventArgs e)
    {
        string userDirectory = profilesDirectory + e.Participant.UserName;      //references user profile directory path
        string userButtons = userDirectory + "/ButtonsPressed.txt";             //references user button data path
        string userSparks = userDirectory + "/SparksSpent.txt";                 //references user sparks data path

        e.CaptureTransaction();     //capture the spark transaction to remove approriate amount of sparks.
        MixerInteractive.TriggerCooldown(e.ControlID, cooldownTimeMS);  //trigger the cooldown of the button being pressed (individual button)

        //LeaderboardSort.GetComponent<LeaderboardSort>().UserLoop();

        if (MixerInteractive.GetButtonDown(e.ControlID))        //Any button with a controlID was pressed down
        {
            Debug.Log(e.Participant.UserName + " pressed down the button: " + e.ControlID + " for " + e.Cost.ToString() + " sparks.");

            if (File.Exists(userButtons))       //make sure the ButtonsPressed.txt exists
            {
                ParseFile(userButtons);         //grab total button presses from data file, assign to buttonsPressedCount
                buttonsPressedCount++;          //increment buttonsPressedCount

                using (StreamWriter buttonText = File.CreateText(userButtons))
                {
                    buttonText.WriteLine(buttonsPressedCount);      //overwrite buttons pressed data with updated button presses
                }

                Debug.Log(e.Participant.UserName + "'s ButtonsPressed data file was updated.");
            }

            if (e.Cost > 0)     //The button costs sparks to press
            {
                Debug.Log("The button costs " + e.Cost + " sparks to press.");

                if (File.Exists(userSparks))       //make sure the SparksSpent.txt exists
                {
                    ParseSparksFile(userSparks);   //grab total sparks spent from data file, assign to sparksSpentCount
                    sparksSpentCount += (int)e.Cost;            //increment sparksSpentCount

                    using (StreamWriter sparkText = File.CreateText(userSparks))
                    {
                        sparkText.WriteLine(sparksSpentCount);      //overwrite sparks spent data with updated sparks spent
                    }
                }
            }
        }
    }`

That should be everything you need to reproduce the issue. If you need more, please let me know.

**Comment by payzer** [comment] 2017-08-03 00:43
Thank you! We'll look at it.

**Comment by payzer** [comment] 2017-08-06 23:47
Ignore, the commit message. This issue is still open.

**Comment by payzer** [comment] 2017-08-06 23:53
I still can't reproduce it on my end. I see my button have a cooldown of 10s which is expected. @PetePinelli and @hoggy077. I know this might sound crazy, but what might be happening is a bug that depends where in the world you are located. @PetePinelli are you also seeing 25 seconds extra? I want to know because if it's a different number then that would confirm my theory.

**Comment by PetePinelli** [comment] 2017-08-07 16:48
@payzer I'm going to download the new release and start a new build of my project, I'll let you know if I'm still having issues. In its current state, my cooldowns do not even want to fire. When an interactive button is pressed it was giving me a debug log code with an error about not having an eTag.

**Comment by payzer** [comment] 2017-08-07 16:54
@PetePinelli sorry, the eTag issue is a recent service deployment we did (we removed eTags which was an internal detail). The latest SDK has a fix for it.

**Comment by PetePinelli** [comment] 2017-08-07 17:43
So I'm still getting the issue where the first button press is the normal 10 second cooldown while the subsequent presses are 8 seconds of shown cooldown with an additional period of time after the cooldown expires that the button is still unclickable.

I decided to see if I was getting the same issue on mobile, and the strangest thing happened.  When I pressed the button on the PC, the cooldown on PC said 8 seconds, where the phone displayed a 15 second cooldown.  I could still press the button on the PC with time remaining on the cooldown being shown on the phone. Pressing the buttons on the phone would cause the 15 second cooldown to appear on the phone but an 8 second cooldown to be displayed on the PC.

I'm really at a loss here.. This is the only script running outside of the mixer package prefab in my scene in a new project in Unity...

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Microsoft.Mixer;

public class CooldownTest : MonoBehaviour {

	// Use this for initialization
	void Start () {

        MixerInteractive.OnInteractiveButtonEvent += OnInteractiveButtonEvent;

        MixerInteractive.GoInteractive();
	}

    public void OnInteractiveButtonEvent(object sender, InteractiveButtonEventArgs e)
    {
        e.CaptureTransaction();
        MixerInteractive.TriggerCooldown(e.ControlID, 10000);
    }
	
	// Update is called once per frame
	void Update () {
		
	}
}
```

**Comment by payzer** [comment] 2017-08-07 17:49
I didn't try twice. Thank you for pointing that out. I'll go try that.

Regarding the mobile issue, I'll let our mobile team know and see if they have any insight into what is going on there. Thank you for bringing that up!

**Comment by payzer** [comment] 2017-08-07 18:16
I'm seeing 10 seconds (I triggered it 4 times) on desktop. I tried on mobile and also got 10 seconds consistently. I also have a blank Unity project.

This is very, very, strange. The only thing I can possibly think of is somehow there's network latency involved? I'll try to find someone on the team who is outside Redmond and see if they can repro.

**Comment by payzer** [comment] 2017-08-07 19:03
We think we know what is going on here. We'll work on a fix.

**Comment by PetePinelli** [comment] 2017-08-07 19:35
Good news! I'll stay posted (:

**Comment by payzer** [comment] 2017-08-07 20:42
I want to set expectations, the fix may be a little while.

**Closed** 2018-02-13 10:11 UTC

**Comment by hoggy077** [comment] 2018-02-13 10:13
Just thought it was time to at least close this issue, considering I haven't encountered the issue, and no one has commented about the issue since August 8th, last year.
