### ISSUE TITLE
Session Already in use ?

### ISSUE THREAD

**Issue by nitinvenu85** [mixer/interactive-unity-plugin#87] opened 2018-06-21 20:12 UTC
We are getting the session already in use somewhere else error.

"Connection failed (error code 4021): You are connected to this session somewhere else. Please disconnect from that session and try again."

We tried restarting Unity. Restarting the PC and we still seem to be getting this error.

**Comment by payzer** [comment] 2018-06-21 20:15
Thank you for reporting this. There is a known service side issue and our service engineers are working on it.

**Comment by payzer** [comment] 2018-06-22 02:19
The issue is now fixed. Thank you for reporting it.

**Closed by payzer** 2018-06-22 02:19 UTC
